### ISSUE TITLE
s2i build is failing for openunison, Can we have a simple way of openunison installation.

### ISSUE THREAD

**Issue by prashanthkumar122** [TremoloSecurity/OpenUnison#522]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  22.934 s
[INFO] Finished at: 2021-03-14T06:23:49Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project openunison-openshift-idm: Could not resolve dependencies for project io.openunison:openunison-openshift-idm:war:1.0.15: The following artifacts could not be resolved: com.tremolosecurity.unison:open-unison-webapp:war:1.0.15, com.tremolosecurity.unison:open-unison-webapp:pom:1.0.15, com.tremolosecurity.unison:openunison-on-undertow:jar:1.0.15: Could not find artifact com.tremolosecurity.unison:open-unison-webapp:war:1.0.15 in Tremolo Security Betas (https://www.tremolosecurity.com/nexus/content/repositories/betas/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
Build failed
ERROR: An error occurred: non-zero (13) exit code from docker.io/tremolosecurity/openunisons2idocker:latest

**Comment by mlbiam** [comment]
What repo are you trying to build?  1.0.15 is quite old and we don't publish it anymore.

**Comment by prashanthkumar122** [comment]
Hi TremoloSecurity/OpenUnison,
Is there any way to install openunison on baremetal kubernetes.
I was following this command 's2i build
https://github.com/TremoloSecurity/openunison-qs-kubernetes.git
docker.io/tremolosecurity/openunisons2idocker:latest
localhost:5000/tremolosecurity/openunison-k8s'
And also followed below mentioned documents, but not able to access
'Openunison' Portal.
https://github.com/OpenUnison/openunison-k8s-login-oidc.
https://github.com/OpenUnison/openunison-k8s-idm-oidc.
https://github.com/TremoloSecurity/openunison-qs-kubernetes.

Will you be able to assist for the installation of Openunison on Kubernetes.

Thanks and regards,
Prashanth

**Comment by mlbiam** [comment]
> I was following this command 's2i build
https://github.com/TremoloSecurity/openunison-qs-kubernetes.git
docker.io/tremolosecurity/openunisons2idocker:latest
localhost:5000/tremolosecurity/openunison-k8s'

This is an old repo, you'll want to choose one of the option from github.com/openunison

> And also followed below mentioned documents, but not able to access
'Openunison' Portal.
https://github.com/OpenUnison/openunison-k8s-login-oidc.
https://github.com/OpenUnison/openunison-k8s-idm-oidc.
https://github.com/TremoloSecurity/openunison-qs-kubernetes.

Are you looking for authentication support or do you want to build self service for namespace-as-a-service?

> Will you be able to assist for the installation of Openunison on Kubernetes.

Yes, please open an issue on the specific repo in the github.com/openunison organization.

**Comment by prashanthkumar122** [comment]
Hi team,
I have installed according to this documentation :'https://github.com/OpenUnison/openunison-k8s-idm-oidc'. I have connected with openid 'keycloak', 
But the issue is, if I enter url : 'https://xxxxx:port', it is redirecting to the keycloak portal, I am not able to view 'openunison' portal. Is it my configuration mistake or Is there any solution for this ??
And also there is one question, can we connect openunison with gitlab for openid??

**Comment by vvarga007** [comment]
I second this: installation is very cumbersome, and documentation needs to be more precise.

**Comment by mlbiam** [comment]
@vvarga007 this repo is going to get retired, we no longer support it.  Please take a look at https://openunison.github.io/ for the latest docs and deployment instructions via Helm
