### ISSUE TITLE
Not able to access openunison dashboard after deploying.

### ISSUE THREAD

**Issue by prashanthkumar122** [TremoloSecurity/OpenUnison#526]
Hi Tremolo team,
I have deployed openunison on kubernetes according to this documentation :'https://github.com/OpenUnison/openunison-k8s-login-oidc'. I have connected with openid 'keycloak',
But the issue is, if I enter url : 'https://xxxxx:port', it is redirecting to the keycloak portal, I am not able to view **'openunison' portal.** Is it my configuration mistake or Is there any solution for this ??

And If I directly enter https://xxxxx:port/auth/oidc/
I am getting below error.
<img width="436" alt="openunison-error" src="https://user-images.githubusercontent.com/58042015/111945372-9e2d6200-8aff-11eb-988f-4314d490bbd8.PNG">

**Comment by mlbiam** [comment]
Since openunison doesn't know who you are, the first thing it will do is redirect you to keycloak for authentication. Once authenticated by keycloak you should be brought back to openunison.

**Comment by prashanthkumar122** [comment]
> Since openunison doesn't know who you are, the first thing it will do is redirect you to keycloak for authentication. Once authenticated by keycloak you should be brought back to openunison.

It is not redirecting back to openunison portal even after authenticating to the keycloak.

**Comment by mlbiam** [comment]
> It is not redirecting back to openunison portal even after authenticating to the keycloak.

I see.  We use this repo for development of core systems discussion.  Please open a ticket on the https://github.com/OpenUnison/openunison-k8s-login-oidc repo and include your values.yaml file you used for creating your orchestra deployment
