### ISSUE TITLE
Status of MyVirtualDirectory and relationship with OpenUnison

### ISSUE THREAD

**Issue by JoelB** [TremoloSecurity/OpenUnison#62]
I'm curious about the decision to integrate your older product MyVirtualDirectory but strip out the LDAP functionality which is arguably critical for most IdM solutions.  Why not bring MyVD back into maintenance and link against it? It seems like that project has been completely abandoned -- the web site is broken and there have been no releases in 7 years. All the while, you are saying that its integration is a feature of OpenUnison.

-Joel

**Comment by mlbiam** [comment]
Joel,

Thanks for reaching out.  You are correct that a virtual directory is a key aspect of identity management deployments.  The short answer is that MyVirtualDirectory is still actively maintained (the last commit was much earlier then seven years ago.  I think I created the 1.0 branch late last year).  We do link to binaries in our pom.xml file (We keep all of the binaries on our own nexus instance at https://www.tremolosecurity.com/nexus) The LDAP listener is not included in OpenUnison for a couple of reasons:

1. OpenUnison is a J2EE application that is designed to run in any Servlet 3.x container (ie Tomcat, Jetty, JBoss/Wildfly, Weblogic, etc) so opening additional ports for LDAP would violate some basic J2EE tenants around services
2. The configurations for MyVD and OpenUnison are 100% compatible.  That is to say you can create an OpenUnison configuration, add the port and TLS configuration properties and drop it right into MyVD (assuming you have added the correct OpenUnison jars into the classpath)

You are correct that the website is really out of date and I apologize for the confusion.  Our plan is to integrate MyVD more into TS.  In the coming weeks we plan to:

1. Migrate MyVD from SourceForge to github
2. Move the documentation from the maven generated site to asciidoc to be consistent with OpenUnison
3. Move the OpenUnison specific inserts from OpenUnison into MyVD

To give you some background, I wrote MyVD long before I founded TS.  Also, TS did not start as an open source company.  After founding TS we continued to develop MyVD and respond to requests on the MyVD mailing lists.  Wether we put an insert into the open source MyVD project or our proprietary Unison product was based on what we perceived at the time as our best competitive advantage.  Once we decided to become an open source company and create OpenUnison we decided to start separating out the proprietary inserts (mostly focussed on Active Directory integration) to make it easier to leverage them in stand-alone MyVD instances.  Once we open sourced OpenUnison, we also open sourced all of the proprietary inserts that we created.

Our focus on integrating MyVD into OpenUnison is not so much to create an LDAP virtual directory that is accessible by applications but to use it as the identity data layer for OpenUnison integration.  All authentication and data lookup goes through the embedded MyVD (except for situations that specifically call the provisioning targets).  This gives you the best of both worlds, you can use the embedded MyVD for OpenUnison to get up and running quickly, and if your applications can use the identity data over LDAP you can stand up a stand-alone MyVD instance using the OpenUnison configuration.

Does this help answer your question?

Thanks
Marc

**Comment by JoelB** [comment]
Thanks for the thorough response, Marc. I wasn't aware that the MyVirtualDirectory project was being actively developed outside of SourceForge -- I'll definitely download the 1.0 branch and test it with our systems. As a user, the [features page](https://www.tremolosecurity.com/openunison/) was a bit confusing since LDAP is listed as a Unison-only feature but it sounds like MyVD can act as the external-facing virtual directory as a compliment to OpenUnison.

Also, thanks very much for your contributions to open source with MyVirtualDirectory and OpenUnison. They seem to be well-developed software and I hope you can gain traction against some of the bigger players in this field.

All the best,
-Joel

**Comment by mlbiam** [comment]
Thanks Joel.  The subversion repo in sourceforge is currently still the authoritative code base for MyVD.  I'd appreciate any testing you do of the 1.0.0 branch (http://sourceforge.net/p/myvd/code/HEAD/tree/branches/MyVD-ApacheDS-2.0M20/) is the 1.0.0 branch.  The only difference between 0.99 and 1.0 is I upgraded the ApacheDS libraries to M20 (we use ApacheDS's LDAP implementation as the LDAP listener).  Thanks for the feedback on the site, we'll update it to make it more clear.

Thanks
Marc
