### ISSUE TITLE
OpenUnision integration with GitHub enterprise 

### ISSUE THREAD

**Issue by patiltussh** [TremoloSecurity/OpenUnison#779]
Can we integrate OpenUnision with GitHub enterprise ?

Current https://openunison.github.io/assets/yaml/openunison-default.yaml file has below 2 configurable parameters -

```
github:
  client_id: d85d77c55a08c9bcbb15
  teams: TremoloSecurity/
```

If we are using GitHub enterprise, how can we define GitHub enterprise hostname/URL(if supported) ?

**Comment by mlbiam** [comment]
We don't right now, but that's mostly because we don't have an enterprise github to test against.  We'll get you a build that you can test.
