### ISSUE TITLE
OpenUnison - AzureAD - K8S - include_auth_chain: "azuread-load-groups" - Could not find user

### ISSUE THREAD

**Issue by druyz** [TremoloSecurity/OpenUnison#933]
Hello,

I Installed ths solution, but I had a problem.

When include_auth_chain: "azuread-load-groups" is enabled, OpenUnison logs an error indicating "Could not find user," and the user is not redirected to the Kubernetes dashboard as expected. When this option is disabled, individual user permissions work, but using group-based permissions still does not.

Pre reqs is OK:
https://www.tremolo.io/post/kubernetes-and-azuread-sso

Kubernetes Version - 1.29

I installed using helm : 
openunison-operator | CHART: openunison-operator-3-0.9 | APP VERSION: 1.0.39
orchestra | CHART: orchestra-2.10.61 | APP VERSION: 1.0.41
orchestra-login-portal | CHART: orchestra-login-portal-2.3.57 | APP VERSION: 1.0.41
orchestra-login-azuread | CHART: orchestra-login-azuread-1.0.3 | APP VERSION: 1.0.30

Image versions OpenUnison: 

operator: 
openunison-kubernetes-operator:1.0.6

orchestra : 
openunison-k8s:1.0.41
activemq-docker:5.18.4
kube-oidc-proxy:1.0.7
python:3:1.0.0

orchestra-login-portal:
openunison-k8s-react:1.0.0

**Comment by mlbiam** [comment]
Please open this issue at https://github.com/openunison/openunison-k8s/issues. Issues on this repo are used for tracking bugs and features for the base platform.   Please include your values.yaml and logs and we'll be happy to help.

**Comment by druyz** [comment]
Thank you very much @mlbiam - https://github.com/OpenUnison/openunison-k8s/issues/130
